// Strings for the hero slideshow (js/hero-slides.js). 8 languages, merged into the main I18N table so t() finds them.
import { I18N } from './i18n.js?v=3.8';

export const HERO_I18N = {
  he: { 'hs.main': 'תמונה ראשית', 'hs.mainAria': 'חזרה לתמונה הראשית', 'hs.live3d': 'תלת־ממד חי', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': 'תלת־ממד חי — גררו כדי לסובב, הקישו על קומה כדי לראות את התכנית', 'hs.loading3d': 'טוען תלת־ממד חי…', 'hs.prev': 'התמונה הקודמת', 'hs.next': 'התמונה הבאה', 'hs.pause': 'עצירת המצגת', 'hs.play': 'הפעלת המצגת', 'hs.region': 'תמונות הפרויקט', 'hs.slide': 'שקופית {n} מתוך {total}', 'hs.illus': 'הדמיה' },
  en: { 'hs.main': 'Main image', 'hs.mainAria': 'Back to the main image', 'hs.live3d': 'Live 3D', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': 'Live 3D — drag to rotate, tap a floor to see its plan', 'hs.loading3d': 'Loading live 3D…', 'hs.prev': 'Previous image', 'hs.next': 'Next image', 'hs.pause': 'Pause slideshow', 'hs.play': 'Play slideshow', 'hs.region': 'Project images', 'hs.slide': 'Slide {n} of {total}', 'hs.illus': 'Visualisation' },
  ro: { 'hs.main': 'Imaginea principală', 'hs.mainAria': 'Înapoi la imaginea principală', 'hs.live3d': '3D live', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': '3D live — trageți pentru a roti, atingeți un etaj pentru a-i vedea planul', 'hs.loading3d': 'Se încarcă 3D live…', 'hs.prev': 'Imaginea anterioară', 'hs.next': 'Imaginea următoare', 'hs.pause': 'Opriți prezentarea', 'hs.play': 'Porniți prezentarea', 'hs.region': 'Imagini ale proiectului', 'hs.slide': 'Imaginea {n} din {total}', 'hs.illus': 'Vizualizare' },
  ru: { 'hs.main': 'Главное фото', 'hs.mainAria': 'Вернуться к главному изображению', 'hs.live3d': '3D онлайн', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': '3D онлайн — потяните, чтобы повернуть, нажмите на этаж, чтобы увидеть план', 'hs.loading3d': 'Загружаем 3D…', 'hs.prev': 'Предыдущее изображение', 'hs.next': 'Следующее изображение', 'hs.pause': 'Остановить показ', 'hs.play': 'Запустить показ', 'hs.region': 'Изображения проекта', 'hs.slide': 'Слайд {n} из {total}', 'hs.illus': 'Визуализация' },
  uk: { 'hs.main': 'Головне фото', 'hs.mainAria': 'Повернутися до головного зображення', 'hs.live3d': '3D наживо', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': '3D наживо — потягніть, щоб повернути, торкніться поверху, щоб побачити план', 'hs.loading3d': 'Завантажуємо 3D…', 'hs.prev': 'Попереднє зображення', 'hs.next': 'Наступне зображення', 'hs.pause': 'Зупинити показ', 'hs.play': 'Запустити показ', 'hs.region': 'Зображення проєкту', 'hs.slide': 'Слайд {n} з {total}', 'hs.illus': 'Візуалізація' },
  fr: { 'hs.main': 'Image principale', 'hs.mainAria': 'Revenir à l’image principale', 'hs.live3d': '3D en direct', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': '3D en direct — faites glisser pour tourner, touchez un étage pour voir son plan', 'hs.loading3d': 'Chargement de la 3D…', 'hs.prev': 'Image précédente', 'hs.next': 'Image suivante', 'hs.pause': 'Mettre le diaporama en pause', 'hs.play': 'Lancer le diaporama', 'hs.region': 'Images du projet', 'hs.slide': 'Image {n} sur {total}', 'hs.illus': 'Visualisation' },
  it: { 'hs.main': 'Immagine principale', 'hs.mainAria': 'Torna all’immagine principale', 'hs.live3d': '3D dal vivo', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': '3D dal vivo — trascina per ruotare, tocca un piano per vederne la pianta', 'hs.loading3d': 'Caricamento del 3D…', 'hs.prev': 'Immagine precedente', 'hs.next': 'Immagine successiva', 'hs.pause': 'Metti in pausa la presentazione', 'hs.play': 'Avvia la presentazione', 'hs.region': 'Immagini del progetto', 'hs.slide': 'Immagine {n} di {total}', 'hs.illus': 'Rendering' },
  de: { 'hs.main': 'Hauptbild', 'hs.mainAria': 'Zurück zum Hauptbild', 'hs.live3d': 'Live-3D', 'hs.cap.real': 'VILNYI RIVER CITY', 'hs.cap.3d': 'Live-3D — ziehen zum Drehen, auf ein Geschoss tippen für den Grundriss', 'hs.loading3d': 'Live-3D wird geladen…', 'hs.prev': 'Vorheriges Bild', 'hs.next': 'Nächstes Bild', 'hs.pause': 'Diashow anhalten', 'hs.play': 'Diashow starten', 'hs.region': 'Projektbilder', 'hs.slide': 'Bild {n} von {total}', 'hs.illus': 'Visualisierung' },
};
for (const l in HERO_I18N) if (I18N[l]) Object.assign(I18N[l], HERO_I18N[l]);
