// Built-in email templates (8 languages). Saved copies in db `templates/{id}` override these.
// Merge fields: {{firstName}} {{lastName}} {{fullName}} {{email}} {{unit}} {{unitLabel}} {{price}} {{amount}} {{dueDate}}
// {{balance}} {{paid}} {{payRef}} {{resNo}} {{stage}} {{docType}} {{docNumber}} {{projectName}} {{signature}}
export const MERGE_FIELDS = ['firstName', 'lastName', 'fullName', 'unit', 'unitLabel', 'price', 'amount', 'dueDate', 'balance', 'paid', 'payRef', 'resNo', 'stage', 'docType', 'docNumber', 'projectName', 'signature'];

const W = {
  en: ['{{firstName}}, thank you for your interest in VILNYI RIVER CITY', 'Dear {{firstName}},\n\nThank you for your interest in VILNYI RIVER CITY — new apartments next to Lacul Morii park in Bucharest.\n\nI would be glad to walk you through the floor plans, the 3D tour and the payment plans, and to answer any question you may have. When would suit you for a short call?\n\nKind regards,\n{{signature}}'],
  he: ['{{firstName}}, תודה על ההתעניינות ב‑VILNYI RIVER CITY', '{{firstName}} שלום,\n\nתודה על ההתעניינות ב‑VILNYI RIVER CITY — דירות חדשות ליד פארק לקול מוריי בבוקרשט.\n\nאשמח להציג לך את התוכניות, את הסיור התלת‑ממדי ואת מסלולי התשלום, ולענות על כל שאלה. מתי נוח לך לשיחה קצרה?\n\nבברכה,\n{{signature}}'],
  ro: ['{{firstName}}, vă mulțumim pentru interesul față de VILNYI RIVER CITY', 'Stimate/Stimată {{firstName}},\n\nVă mulțumim pentru interesul față de VILNYI RIVER CITY — apartamente noi lângă parcul Lacul Morii din București.\n\nVă prezint cu plăcere planurile, turul 3D și planurile de plată și răspund oricărei întrebări. Când v-ar conveni o scurtă discuție telefonică?\n\nCu stimă,\n{{signature}}'],
  ru: ['{{firstName}}, спасибо за интерес к VILNYI RIVER CITY', 'Здравствуйте, {{firstName}}!\n\nБлагодарим за интерес к VILNYI RIVER CITY — новым квартирам рядом с парком Лакул Морий в Бухаресте.\n\nС удовольствием покажу планировки, 3D‑тур и варианты оплаты и отвечу на любые вопросы. Когда вам удобно коротко созвониться?\n\nС уважением,\n{{signature}}'],
  uk: ['{{firstName}}, дякуємо за інтерес до VILNYI RIVER CITY', 'Вітаю, {{firstName}}!\n\nДякуємо за інтерес до VILNYI RIVER CITY — нових квартир поруч із парком Лакул Морій у Бухаресті.\n\nІз задоволенням покажу планування, 3D‑тур і варіанти оплати та відповім на будь‑які запитання. Коли вам зручно коротко поспілкуватися?\n\nЗ повагою,\n{{signature}}'],
  fr: ['{{firstName}}, merci de votre intérêt pour VILNYI RIVER CITY', 'Bonjour {{firstName}},\n\nMerci de votre intérêt pour VILNYI RIVER CITY — des appartements neufs à côté du parc Lacul Morii, à Bucarest.\n\nJe serai ravi de vous présenter les plans, la visite 3D et les modalités de paiement, et de répondre à vos questions. Quand seriez-vous disponible pour un court appel ?\n\nBien cordialement,\n{{signature}}'],
  it: ['{{firstName}}, grazie per l’interesse per VILNYI RIVER CITY', 'Gentile {{firstName}},\n\ngrazie per l’interesse per VILNYI RIVER CITY — nuovi appartamenti accanto al parco Lacul Morii a Bucarest.\n\nSarò lieto di illustrarle le planimetrie, il tour 3D e i piani di pagamento e di rispondere a ogni domanda. Quando le sarebbe comodo sentirci brevemente?\n\nCordiali saluti,\n{{signature}}'],
  de: ['{{firstName}}, vielen Dank für Ihr Interesse an VILNYI RIVER CITY', 'Guten Tag {{firstName}},\n\nvielen Dank für Ihr Interesse an VILNYI RIVER CITY – neue Wohnungen direkt am Park Lacul Morii in Bukarest.\n\nGerne zeige ich Ihnen die Grundrisse, den 3D‑Rundgang und die Zahlungspläne und beantworte Ihre Fragen. Wann passt Ihnen ein kurzes Telefonat?\n\nMit freundlichen Grüßen\n{{signature}}'],
};
const R = {
  en: ['Payment reminder — apartment {{unit}}', 'Dear {{firstName}},\n\nThis is a friendly reminder that the next instalment for apartment {{unitLabel}} — {{amount}} — is due on {{dueDate}}.\n\nPlease use the payment reference {{payRef}}. If you have already made the transfer, please disregard this message.\n\nKind regards,\n{{signature}}'],
  he: ['תזכורת תשלום — דירה {{unit}}', '{{firstName}} שלום,\n\nזוהי תזכורת ידידותית שהתשלום הבא עבור הדירה {{unitLabel}} — {{amount}} — מועד פירעונו {{dueDate}}.\n\nנא לציין את אסמכתת התשלום {{payRef}}. אם ההעברה כבר בוצעה, אפשר להתעלם מהודעה זו.\n\nבברכה,\n{{signature}}'],
  ro: ['Memento plată — apartamentul {{unit}}', 'Stimate/Stimată {{firstName}},\n\nVă reamintim că următoarea tranșă pentru apartamentul {{unitLabel}} — {{amount}} — este scadentă la {{dueDate}}.\n\nVă rugăm să folosiți referința de plată {{payRef}}. Dacă ați efectuat deja transferul, vă rugăm să ignorați acest mesaj.\n\nCu stimă,\n{{signature}}'],
  ru: ['Напоминание об оплате — квартира {{unit}}', 'Здравствуйте, {{firstName}}!\n\nНапоминаем, что следующий платёж по квартире {{unitLabel}} — {{amount}} — необходимо внести до {{dueDate}}.\n\nПожалуйста, укажите назначение платежа {{payRef}}. Если перевод уже выполнен, просто проигнорируйте это письмо.\n\nС уважением,\n{{signature}}'],
  uk: ['Нагадування про оплату — квартира {{unit}}', 'Вітаю, {{firstName}}!\n\nНагадуємо, що наступний платіж за квартиру {{unitLabel}} — {{amount}} — слід сплатити до {{dueDate}}.\n\nБудь ласка, вкажіть призначення платежу {{payRef}}. Якщо переказ уже здійснено, просто проігноруйте цей лист.\n\nЗ повагою,\n{{signature}}'],
  fr: ['Rappel de paiement — appartement {{unit}}', 'Bonjour {{firstName}},\n\nNous vous rappelons que la prochaine échéance pour l’appartement {{unitLabel}} — {{amount}} — est due le {{dueDate}}.\n\nMerci d’indiquer la référence {{payRef}}. Si le virement a déjà été effectué, veuillez ne pas tenir compte de ce message.\n\nBien cordialement,\n{{signature}}'],
  it: ['Promemoria di pagamento — appartamento {{unit}}', 'Gentile {{firstName}},\n\nle ricordiamo che la prossima rata per l’appartamento {{unitLabel}} — {{amount}} — scade il {{dueDate}}.\n\nLa preghiamo di indicare il riferimento {{payRef}}. Se ha già effettuato il bonifico, ignori pure questo messaggio.\n\nCordiali saluti,\n{{signature}}'],
  de: ['Zahlungserinnerung – Wohnung {{unit}}', 'Guten Tag {{firstName}},\n\nwir möchten Sie freundlich daran erinnern, dass die nächste Rate für die Wohnung {{unitLabel}} – {{amount}} – am {{dueDate}} fällig ist.\n\nBitte verwenden Sie den Verwendungszweck {{payRef}}. Falls Sie bereits überwiesen haben, betrachten Sie diese Nachricht bitte als gegenstandslos.\n\nMit freundlichen Grüßen\n{{signature}}'],
};
const U = {
  en: ['VILNYI RIVER CITY — project update', 'Dear {{firstName}},\n\nWe are pleased to share the latest progress on VILNYI RIVER CITY, buildings C3 & C4.\n\n[Write the update here]\n\nThank you for your trust,\n{{signature}}'],
  he: ['VILNYI RIVER CITY — עדכון מהפרויקט', '{{firstName}} שלום,\n\nשמחים לשתף את ההתקדמות האחרונה בפרויקט VILNYI RIVER CITY, בניינים C3 ו‑C4.\n\n[כתבו כאן את העדכון]\n\nתודה על האמון,\n{{signature}}'],
  ro: ['VILNYI RIVER CITY — noutăți din proiect', 'Stimate/Stimată {{firstName}},\n\nNe bucurăm să vă prezentăm cele mai recente progrese ale proiectului VILNYI RIVER CITY, blocurile C3 și C4.\n\n[Scrieți aici actualizarea]\n\nVă mulțumim pentru încredere,\n{{signature}}'],
  ru: ['VILNYI RIVER CITY — новости проекта', 'Здравствуйте, {{firstName}}!\n\nРады поделиться последними новостями о ходе строительства VILNYI RIVER CITY, корпуса C3 и C4.\n\n[Напишите здесь новости]\n\nСпасибо за доверие,\n{{signature}}'],
  uk: ['VILNYI RIVER CITY — новини проєкту', 'Вітаю, {{firstName}}!\n\nРаді поділитися останніми новинами про хід будівництва VILNYI RIVER CITY, корпуси C3 і C4.\n\n[Напишіть тут новини]\n\nДякуємо за довіру,\n{{signature}}'],
  fr: ['VILNYI RIVER CITY — point d’avancement', 'Bonjour {{firstName}},\n\nNous avons le plaisir de vous présenter l’avancement de VILNYI RIVER CITY, bâtiments C3 et C4.\n\n[Rédigez ici le point d’avancement]\n\nMerci de votre confiance,\n{{signature}}'],
  it: ['VILNYI RIVER CITY — aggiornamento sul progetto', 'Gentile {{firstName}},\n\nsiamo lieti di condividere gli ultimi progressi di VILNYI RIVER CITY, edifici C3 e C4.\n\n[Scriva qui l’aggiornamento]\n\nGrazie per la fiducia,\n{{signature}}'],
  de: ['VILNYI RIVER CITY – Neuigkeiten zum Projekt', 'Guten Tag {{firstName}},\n\ngerne informieren wir Sie über den aktuellen Baufortschritt von VILNYI RIVER CITY, Häuser C3 und C4.\n\n[Hier die Neuigkeiten einfügen]\n\nVielen Dank für Ihr Vertrauen\n{{signature}}'],
};
const D = {
  en: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Dear {{firstName}},\n\nPlease find attached {{docType}} {{docNumber}} for apartment {{unitLabel}}.\n\nKind regards,\n{{signature}}'],
  he: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', '{{firstName}} שלום,\n\nמצורף {{docType}} {{docNumber}} עבור הדירה {{unitLabel}}.\n\nבברכה,\n{{signature}}'],
  ro: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Stimate/Stimată {{firstName}},\n\nVă transmitem atașat {{docType}} {{docNumber}} pentru apartamentul {{unitLabel}}.\n\nCu stimă,\n{{signature}}'],
  ru: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Здравствуйте, {{firstName}}!\n\nВо вложении — {{docType}} {{docNumber}} по квартире {{unitLabel}}.\n\nС уважением,\n{{signature}}'],
  uk: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Вітаю, {{firstName}}!\n\nУ вкладенні — {{docType}} {{docNumber}} щодо квартири {{unitLabel}}.\n\nЗ повагою,\n{{signature}}'],
  fr: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Bonjour {{firstName}},\n\nVeuillez trouver ci-joint le document {{docType}} {{docNumber}} pour l’appartement {{unitLabel}}.\n\nBien cordialement,\n{{signature}}'],
  it: ['{{docType}} {{docNumber}} — VILNYI RIVER CITY', 'Gentile {{firstName}},\n\nin allegato il documento {{docType}} {{docNumber}} per l’appartamento {{unitLabel}}.\n\nCordiali saluti,\n{{signature}}'],
  de: ['{{docType}} {{docNumber}} – VILNYI RIVER CITY', 'Guten Tag {{firstName}},\n\nim Anhang erhalten Sie {{docType}} {{docNumber}} für die Wohnung {{unitLabel}}.\n\nMit freundlichen Grüßen\n{{signature}}'],
};
const mk = (src) => ({ subject: Object.fromEntries(Object.entries(src).map(([l, v]) => [l, v[0]])), body: Object.fromEntries(Object.entries(src).map(([l, v]) => [l, v[1]])) });
export const BUILTIN_TEMPLATES = {
  tpl_welcome: { name: { en: 'Welcome / first contact', he: 'ברוכים הבאים / פנייה ראשונה' }, ...mk(W), builtin: true },
  tpl_reminder: { name: { en: 'Payment reminder', he: 'תזכורת תשלום' }, ...mk(R), builtin: true },
  tpl_update: { name: { en: 'Project update', he: 'עדכון פרויקט' }, ...mk(U), builtin: true },
  tpl_document: { name: { en: 'Send a document', he: 'שליחת מסמך' }, ...mk(D), builtin: true },
};
